### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by osipxd** [EndlessCodeGroup/ECInventory#13]
It will be better to rename RPGInv3 to something else because it is very different from RPGInv:
- Configs are not compatible with RPGInv
- it gives the ability to create multiple inventories (inventories may be bound to players, entities and items)
- it will not have pets, items, craft extensions, and other features not related to inventory functionality
- it will give more control on player's inventories
- it will provide API to create custom inventories from code

**Comment by VacAge** [comment]
- EndlessInventory
- BetterInv
- InvApi
- InventoryApi

**Comment by osipxd** [comment]
`ECInv`, `ECInventory`, or `ECInventories` where EC = EndlessCode, and pronounced similar to "easy"

**Comment by osipxd** [comment]
`EC Inventory` is the winner!
